### ISSUE TITLE
建议：希望能够将各个市场平等看待作为商店信息

### ISSUE THREAD

**Issue by LaoshuBaby** [CnGal/CnGalWebSite#119]
例如我们以一款有Taptap和Steam同时发行的游戏为例
![图片](https://user-images.githubusercontent.com/42690037/170057063-c82ce71e-cf51-4906-bd6e-97737faaf8e9.png)

这一个板块的题目直接叫Steam信息，而Taptap则被放在了下面的相关网站上。

又或者是同时在NS上也有销售的WILL美好世界：

![图片](https://user-images.githubusercontent.com/42690037/170057335-93eacb6a-d8c4-4447-bd5c-aa2fbb7d91c9.png)

它在NS，Taptap两套商店/应用市场里面均有提供，是可以直接搞到对应的索引的。

能否对于Steam应用、Taptap应用等，都采取和之前#93 中提到的索引支持一样，大量的索引化填写，减少复制URL的麻烦？

当然这估计又得意味着后端的一堆大改了（挠头）

好处是可以直接用爬虫从Wikidata上面爬取对应的标识符进来。

比如Steam应用对应的是[P1733](https://www.wikidata.org/wiki/Property:P1733)，Taptap对应的是[P9297](https://www.wikidata.org/wiki/Property:P9297)，NS的eShop对应的是[P8084](https://www.wikidata.org/wiki/Property:P8084)

Apple Store和GPlay的我还没找，不好找了应该。

----

F12简单改了一个效果出来，差不多是这意思？

![图片](https://user-images.githubusercontent.com/42690037/170059724-adc2bd9b-ccf6-49cd-983d-bb0b7f2442d9.png)

**Comment by LittleFish-233** [comment]
#大部分国G会在Steam发售，我们因此对Steam进行了大量优化，包括主图尺寸适配，折扣页面，汇总页面......
如果将各个平等看待作为商店信息，需要重构大量代码

每个市场的价格和折扣信息是不一致的，可能需要单独制作卡片

TapTap和NS平台的作品数量并不多，目前可以继续放在相关网站里

放暑假来研究一下

**Comment by LittleFish-233** [comment]
@LaoshuBaby  参考 `vndb` 中的 `Releases` 列表，或者 `月幕` 的 `发行列表`

![image](https://user-images.githubusercontent.com/53342258/232264274-d741c90d-7c6d-4d95-95b4-d69233543d21.png)

![image](https://user-images.githubusercontent.com/53342258/232264282-8b0b7b1d-e94c-4b6a-b87e-40c0057334a2.png)

我们也可以采用类似的方式，只需要修改一些字段就行

虽然是这么说，但是涉及到 `Steam信息` 的所有逻辑，发行日期排序之类的，可能挺麻烦的，工期定为一周吧
