### ISSUE TITLE
请求：把cngal加入Blazor.Cropper的使用者名单

### ISSUE THREAD

**Issue by Chronostasys** [CnGal/CnGalWebSite#120]
您好，我是[Blazor.Cropper](https://github.com/Chronostasys/Blazor.Cropper)的开发者，非常高兴看到有国人将我写的库用到了实际项目中，不知能否把贵站在加入Cropper项目Readme的使用者名单中？  
Cropper存在的问题也请直接告诉我，我会尽量改进！

**Comment by LittleFish-233** [comment]
当然可以ヾ(•ω•`)o
[Blazor.Cropper](https://github.com/Chronostasys/Blazor.Cropper)是十分优秀的组件库，对于我这样不熟悉js的开发者来说十分友好ヾ(^▽^*)))
我们从21年夏天开始用它来裁剪图片，这将近一年的时间里，除了升级 .Net 6 时踩了一点坑之外，Blazor.Cropper表现得十分稳定(ง •_•)ง

**Comment by Chronostasys** [comment]
好的，非常感谢你的反馈，祝cngal越做越好！
