### ISSUE TITLE
需求：对网盘类下载提供结构化支持而非一长串提取码链接

### ISSUE THREAD

**Issue by LaoshuBaby** [CnGal/CnGalWebSite#161]
**你的功能是为了解决一个现有问题吗？**
是的，经常有一些小作品采用网盘分享作为外部链接，而他们的提取码和链接可能是混杂在一起的

![图片](https://user-images.githubusercontent.com/42690037/175579629-30ba82da-41c4-405e-aaa2-d08c975a58e8.png)

**描述你想要的解决方式**
类似现有的结构化方式（#93 ），允许指定网盘厂商（百度、阿里）和链接部分自动识别（#122 ），结构化提取码（甚至可以尝试自动组装，百度的链接是可以把提取码作为参数在URL里面传递的）

**其他内容**
可能没多少需求，建议不用排期很靠前，排future就行了，只是看到了就提一句罢了，万一哪一年开发人员闲了再写就是。

不过至少先给百度盘之类的加个LOGO吧233（也不急）

**Comment by LittleFish-233** [comment]
根据[《词条编辑规范》](https://www.cngal.org/articles/index/2)中的描述

> 相关网站中请填写官方发布页，各大游戏平台等链接；其他Wiki类站点请在关联信息中填写

百度网盘链接应放到附加信息中的相关网站部分，上图词条是因为导入旧数据时没有正确处理，正确方式如下图

![image](https://user-images.githubusercontent.com/53342258/175757384-df446745-f0a7-499e-990d-1e9a80fb0eb1.png)

不过确实需要结构化方式和自动识别
感觉有点像资源站了（×
排期往后吧，资源下载什么的也不是主要任务

**Comment by LittleFish-233** [comment]
资源下载并不是资料站的主要任务，无限期延后
