### ISSUE TITLE
缺陷：部分基于标识符的外部链接会重复显示

### ISSUE THREAD

**Issue by LaoshuBaby** [CnGal/CnGalWebSite#190]
**描述Bug**
部分基于标识符的外部链接会重复显示

![图片](https://user-images.githubusercontent.com/42690037/178105501-a9936517-b0b9-43f7-add6-7fe4dc285b84.png)

![图片](https://user-images.githubusercontent.com/42690037/178105510-bb5d81d3-42a4-45a2-a8b2-4876d18cf217.png)

![图片](https://user-images.githubusercontent.com/42690037/178105525-36d22827-2590-4ddc-a8d4-6b52092f6f28.png)

**如何复现**
https://app.cngal.org/entries/index/3652
访问即可，看右边

**预期结果**
略

**屏幕截图**
略
**目标平台（请选择你遇到问题的平台）:**
PC，网页版，火狐Nightly 无痕模式

**其他内容**
已登录账号，是app模式

**Comment by LittleFish-233** [comment]
可能是bgm两种不同的域名导致的，我排查一下

**Comment by LaoshuBaby** [comment]
> 可能是bgm两种不同的域名导致的

但是出问题的是VNDB和Wikidata（好像都是鼠宝宝常干的，该不会是我干的吧）

Bangumi倒是没重复

（而且对于VN本身用的bangumi都是subject吧 https://bgm.tv/subject/374337 ）

**Comment by LittleFish-233** [comment]
啊，没还没看那个链接（×

看起来，是增删比较算法的问题，看板娘连续十几天都在补全了orz

![image](https://user-images.githubusercontent.com/53342258/178105861-75d99aec-8afd-44ea-af6f-2622a0a7485d.png)

**Comment by LittleFish-233** [comment]
之前迁移自定义链接的时候，没有处理大小写的问题，导致循环生成审核记录
重新保存一遍关联信息就好
后台扫描了一下，有问题的都已修复
（十分感谢，不然看板娘每天都要辛辛苦苦地补全×
