### ISSUE TITLE
问题：为何获取所有Entries需要管理员权限

### ISSUE THREAD

**Issue by LaoshuBaby** [CnGal/CnGalWebSite#308]
以获取条目信息为例：（接续之前QQ群的讨论）

https://github.com/CnGal/CnGalWebSite/blob/408c430c7372e2ecfdc8bf8afa58de13f9a738b2/CnGalWebSite/CnGalWebSite.Shared/Component/Admin/Entries/ListEntries.razor#L64-L75

该段代码在[Swagger](https://www.cngal.org/swagger/index.html)上对应的API为：

![图片](https://user-images.githubusercontent.com/42690037/194015555-d6ac4c62-52e7-4c12-b141-e8ecd04c09cf.png)

对于数据终端用户，在Swagger上只能找到获取单个游戏条目的API，需要带参数`{id}`：

![图片](https://user-images.githubusercontent.com/42690037/194015865-75e8cda4-63c2-4e5e-b21d-1a1993b26b24.png)

要获取所有数据，只能从 app.cngal.org/data 人工导出数据，但这里导出确实只有metadata，各种关联数据都不包含

![图片](https://user-images.githubusercontent.com/42690037/194016798-fe6b93fb-6d7d-4b00-8200-140a36501cf4.png)

![图片](https://user-images.githubusercontent.com/42690037/194017307-265c96fa-0a30-4dae-adbf-8dc1179fa8a4.png)

![图片](https://user-images.githubusercontent.com/42690037/194017626-c23d865c-4691-4af2-bb2e-bac05e605b3a.png)

---

~~此外，贵站的swagger实在太慢，不管火狐还是谷歌都一样。当然我知道这是上游问题（https://github.com/caspar-chen/swagger-ui-layer/issues/33 ），但是这个不吐槽觉得实在对不住点开一个折叠菜单的焦躁~~

**Comment by LittleFish-233** [comment]
不好意思隔了这么久才看到

实际上管理员的接口也只能获取到 `metadata`，如下所示是 `api/admin/listentries` 返回的数据模型定义，明显数据更少了

```csharp
public class ListEntryAloneModel
    {
        [Display(Name = "Id")]
        public int Id { get; set; }
        [Display(Name = "类型")]
        public EntryType? Type { get; set; } = null;
        [Display(Name = "唯一名称")]
        public string Name { get; set; }

        [Display(Name = "显示名称")]
        public string DisplayName { get; set; }

        [Display(Name = "简介")]
        public string BriefIntroduction { get; set; }
        [Display(Name = "优先级")]
        public int Priority { get; set; }
        [Display(Name = "是否隐藏")]
        public bool IsHidden { get; set; }
        [Display(Name = "可否评论")]
        public bool CanComment { get; set; }
    }
```

推荐的做法是，获取到 `Id` 列表，再逐个调用获取单个词条数据的API，不便之处敬请谅解

**Comment by LittleFish-233** [comment]
对了，推荐使用  `/api/entries/GetAllEntriesIdName` 获取全部词条Id

**Comment by LaoshuBaby** [comment]
> 对了，推荐使用 `/api/entries/GetAllEntriesIdName` 获取全部词条Id

原来用这个！因为这个带Name，不是直接一个大大的ID摆在脸前，所以没有发觉这是需要的那个listAll的API

（而且因为摆在最底下，没翻到，这个确实是我的锅，这个Issue目的就是为了找到一个API能获取所有条目ID来着）

感谢耐心回复φ(゜▽゜*)♪
