### ISSUE TITLE
缺陷：同名条目合并难以分清目标

### ISSUE THREAD

**Issue by LaoshuBaby** [CnGal/CnGalWebSite#319]
**描述Bug**
合并同名条目

**如何复现**

条目A https://www.cngal.org/entries/index/824
![图片](https://user-images.githubusercontent.com/42690037/197353849-0ec92a71-65d2-4821-b3cf-35294df6cf67.png)

条目B https://www.cngal.org/entries/index/4547
![图片](https://user-images.githubusercontent.com/42690037/197353866-d56ad1f2-79db-4efb-a28d-50a0594a0f43.png)

点右下角的合并条目
![图片](https://user-images.githubusercontent.com/42690037/197353985-50e13c0c-28d0-4aaf-9912-7b8614eced56.png)

不能提示到底谁合并到谁
[录屏 2022年10月23日 01时26分32秒.webm](https://user-images.githubusercontent.com/42690037/197354094-fc9caabf-6603-4bd0-8c59-177af9b45282.webm)

如果恰好选择了同一个，则会在右下角提示：
![图片](https://user-images.githubusercontent.com/42690037/197354049-c6f2688a-0868-456c-87eb-e7da6ddba529.png)

但是，依然没法知道到底是824在目标里还是4547在目标里

**预期结果**
在条目名称后会注明序号，如`鼠宝宝(#114)`和`鼠宝宝(#514)`

**目标平台（请选择你遇到问题的平台）:**
网站

**Comment by LittleFish-233** [comment]
> 预期结果
在条目名称后会注明序号，如 `鼠宝宝(#114)` 和 `鼠宝宝(#514)`

我太菜了，所以没法实现。
但是我们正在使用Vue3重构前端（[CnGalWebSite.VueTrial](https://github.com/CnGal/CnGalWebSite.VueTrial)），可以关注一下

> 但是，依然没法知道到底是824在目标里还是4547在目标里

因为我们不支持创建同名词条，所以词条名称必然存在区别
举例来说，`#4547` 和 `#824` 的区别是 `#4547` 多了一个后导空格
可以点进编辑页面或者按F12检查元素进行查看

> 然后刚好合并反了orz

**Comment by LittleFish-233** [comment]
这个问题会由 #262 修复，先关闭
