### ISSUE TITLE
需求：在API中明确所有时间值的时区

### ISSUE THREAD

**Issue by chengyuhui** [CnGal/CnGalWebSite#333]
**你的功能是为了解决一个现有问题吗？**
目前我正在为CnGal创建RSS源（DIYgod/RSSHub#11203），在查看API时发现部分接口返回的时间值似乎并不是很好进行准确解析，例如 https://www.cngal.org/api/entries/GetEntryView/3434
```json
{
    "title": "我们将《十二刻度的月时计》作为一个DLC加入《蔚蓝月下的回忆》中啦！",
    "briefIntroduction": "在各位小伙伴的强烈要求下，我们将《十二刻度的月时计》作为一个DLC加入《蔚蓝月下的回忆》中啦！若是购买了DLC，各位小伙伴在完成17日寻找《十二刻度的月计时》剧情后的手机界面中就会多出一个游戏app，或是直接在游戏主界面内进入游戏。\n\n《十二刻度的月时计》是《蔚蓝月下的回忆》的前传，讲述了轮回的起因与夜巧玥是如何与林灵结下仇怨。\n叶灵：原来站在你的背后是这样一种感觉。\n夜巧玥：这次是我站在他的背后，不是你！\n\n......",
    "link": "https://weibo.com/6398448873/MbMNewueA",
    "groupName": "星愿游戏制作组",
    "groupId": 3434,
    "newsType": "动态",
    "image": "https://image.cngal.org/images/2022/01/23/66a3bc509d6b.jpg",
    "userId": null,
    "happenedTime": "2022-10-24T13:43:52"
}
```

`happenedTime`字段虽然采用了ISO日期格式，但并未明确时区（如`Z`表示UTC，`+08:00`表示UTC+8），这种日期表达方式在不同的环境下可能导致不同的解析方式，最终使得API用户获得的时间出现时区上差错（例如，如果运行脚本的服务器并不在UTC+8时区，就可能转换成错误的时间戳），进行时区变更有时也需要额外的库或者工具，不是很方便。

**描述你想要的解决方式**
在日期值中明确时区（加上`Z`或者时区值）。

**描述你考虑过的解决方案**
从上面提到的那个API输出看来，项目内存在至少两种日期输出方式，其中一种带有毫秒值，这些可能都需要修改，但是在前端`new Date(...)`的话应该也不会造成问题。

**其他内容**
暂无

**Comment by LittleFish-233** [comment]
抱歉过了这么久才看到<(＿　＿)>

目前站内的日期储存并没哟包含时区，应该所有的输出时间都是 `UTC+8`  ;时间输出应该都带有毫秒值，没有带的是毫秒值为0省略了

近期我们会尝试给所有日期添加上时区，并统一输出格式

非常感谢你为CnGal创建了RSS源，有一个小问题是API获取到的 `briefIntroduction` 里面换行是用 `\n` 表示的，可以在脚本里转换成 `<br>` 这样用户体验会好一点 o((>ω< ))o

**Comment by chengyuhui** [comment]
> 非常感谢你为CnGal创建了RSS源，有一个小问题是API获取到的 `briefIntroduction` 里面换行是用 `\n` 表示的，可以在脚本里转换成 `<br>` 这样用户体验会好一点 o((>ω< ))o

当时疏忽了，后面另外提了PR修复这个问题，现在线上的版本应该没有这个问题了
