### ISSUE TITLE
需求：（不急，纯属吐槽）个人主页瓷砖格重新布局

### ISSUE THREAD

**Issue by LaoshuBaby** [CnGal/CnGalWebSite#497]
**你的功能是为了解决一个现有问题吗？**
![图片](https://user-images.githubusercontent.com/42690037/230802175-994fd1b9-78a0-4d42-952d-227704c26993.png)

上55下2的看的人尴尬症都犯了，因为刚刚改了个人简介露出来才发现这两部分是被拉伸成了这种形状（此时浏览器窗口是2560*1440的屏幕全屏了，125%）

（但是仔细抱着“肯定有响应式设计吧”的心态去拖动浏览器窗口，果然有变化，哎这下就正常了：
![图片](https://user-images.githubusercontent.com/42690037/230802266-b64ea40c-6053-440a-8828-37d91e34d59c.png)

继续缩还有其他情况：

<table>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/42690037/230802318-97557c50-1244-4544-a8e5-95fff70ad190.png" alt="image1"></td>
    <td><img src="https://user-images.githubusercontent.com/42690037/230802335-48149ee0-69ae-46e9-b75f-1cc46ef235c1.png" alt="image2"></td>
    <td><img src="https://user-images.githubusercontent.com/42690037/230802339-1361756b-4a9d-4f92-8bc7-f5dda74c9b8a.png" alt="image3"></td>
    <td><img src="https://user-images.githubusercontent.com/42690037/230802348-384c417c-5c3b-472c-a934-5c895a11c791.png" alt="image4"></td>
    <td><img src="https://user-images.githubusercontent.com/42690037/230802366-c54f5b7b-4531-4d27-a4c2-06975887701e.png" alt="image5"></td>
  </tr>
</table>

---

**描述你想要的解决方式**
改成固定`3row*4cloumn`的形式或者在宽屏的时候变`4*3`/`2*6`等其他整除布局，或者和github一样的长条型瓷砖格

**描述你考虑过的解决方案**
（不会前端）

**Comment by LittleFish-233** [comment]
好的，我改成EChart实现吧
