### ISSUE TITLE
缺陷：Safari适配问题

### ISSUE THREAD

**Issue by ShinonomeSetsuna** [CnGal/CnGalWebSite#732]
**描述Bug**
在Safari浏览器部分图片高度异常。

**如何复现**
实用Safari访问网页就能看到

**预期结果**
图片正常显示。

**屏幕截图**
<img width="1470" alt="截屏2023-11-29 14 31 20" src="https://github.com/CnGal/CnGalWebSite/assets/114331286/e8088905-9634-46a2-b41c-07ce69de4bec">

**目标平台（请选择你遇到问题的平台）:**
网站
iOS版本14.1.1 (23B81)
Safari版本17.1 (19616.2.9.11.7)

**其他内容**
在`#home-page .item img, #home-page .item .image`中添加`height: 100%;`即可，虽然我也不知道怎么修复的。

**Comment by LittleFish-233** [comment]
非常感谢提交Issue，目前已经修复，可以尝试ctrl+f5清除缓存后浏览，如果还有哪里遗漏的地方欢迎补充~
