### ISSUE TITLE
需求：小黑盒APPID

### ISSUE THREAD

**Issue by LaoshuBaby** [CnGal/CnGalWebSite#734]
和steamid等并列，便于数据工作人员索引小黑盒上的评价评分情况，与Steam数据综合分析

https://github.com/Hellobaka/SteamHeyboxQuery/blob/fa96d9439f55baa3e6fdc6d10143131cf4734d79/me.cqp.luohuaming.SteamHeyboxQuery.PublicInfos/WebApi/GetGameInfo.cs#L8

**Comment by LittleFish-233** [comment]
`SteamId` 储存在发行列表中，小黑盒并非第一方发行平台，因此和 `SteamId` 并列不合适。
可以将小黑盒APPID添加到外部链接中
