### ISSUE TITLE
需求：建议允许罗列多个不同的QQ群并且添加备注

### ISSUE THREAD

**Issue by LaoshuBaby** [CnGal/CnGalWebSite#767]
**你的功能是为了解决一个现有问题吗？**
目前部分热门游戏同时都有多个并行的QQ群，并且可能会按照是否允许剧透和发言频率等做出限制，希望能更好的注明

![图片](https://github.com/CnGal/CnGalWebSite/assets/42690037/11801c92-b192-486e-b9e9-6dbd8f0f4595)
![图片](https://github.com/CnGal/CnGalWebSite/assets/42690037/c15e742b-b688-446d-87ec-75e4ad4ebcf7)
![图片](https://github.com/CnGal/CnGalWebSite/assets/42690037/484eaeb9-1870-43eb-a715-2fb6d4924b04)
![图片](https://github.com/CnGal/CnGalWebSite/assets/42690037/f680f3e6-2337-4d7a-a83e-1e7f4f54cb01)

**描述你想要的解决方式**
![图片](https://github.com/CnGal/CnGalWebSite/assets/42690037/7d2e04d5-77b3-4962-8481-0aedfb9d997a)
允许以自然文本的形式填写群名，并自动探测其中首个出现的超过6位的连续出现的数字作为群号（因为可能还会有“回答问题是<code>12345678</code>”），如果可能的话自动生成点击进群的链接（不太可行，但是字体上做变化是建议的）

**Comment by LittleFish-233** [comment]
目前允许允许以自然文本的形式填写群名，并且可以使用逗号或顿号分割多个群

用列表形式展示QQ群，并加粗群号的功能会在五一假期时完成。

**Comment by LittleFish-233** [comment]
用列表展示需要修改输入数据的格式，综合考虑还是保持原先的纯文本格式。

《饿殍：明末千里行》的例子可以改为：`685288213 （官方1群，已满），591088298（官方2群，已满），925491281（官方3群）`

群号已自动加粗
