### ISSUE TITLE
缺陷：留言板切换编辑器报错

### ISSUE THREAD

**Issue by xiaoxustudio** [CnGal/CnGalWebSite#783]
**描述Bug**
在文章详情界面的留言板，点击多次切换编辑器会出现错误

**如何复现**
复现的步骤
1. 进入文章详情界面
2. 转到留言板位置
3. 重复点击切换编辑器
4. 遇到问题

**预期结果**
应该正确的切换编辑器而不会报错

**屏幕截图**
![image](https://github.com/CnGal/CnGalWebSite/assets/52703373/eb428582-e3c6-4aba-a159-cf0b7daacd60)

**目标平台（请选择你遇到问题的平台）:**
 - 类型：网站
 - 操作系统：Windows 11
 - 浏览器：Edge
 - 版本：126.0.2592.68 (64 位)

**Comment by LittleFish-233** [comment]
等待编辑器完全加载后再切换可以临时规避此问题。

将在两周内修复
