### ISSUE TITLE
需求：添加对基于标识符的知识图谱索引支持

### ISSUE THREAD

**Issue by LaoshuBaby** [CnGal/CnGalWebSite#93]
**你的功能是为了解决一个现有问题吗？**
是的，目前每次填写标识符都非常麻烦
（别看Issue名字这么夸张，其实说白了就是打ID打累了）
（感觉这个Issue只能解决我一个人的需求？毕竟我目前没看到有其他知识图谱爱好者（逃））

**描述你想要的解决方式**
能够快速检索常见的标识符系统，快速填写Key本身

**描述你考虑过的解决方案**
这个要看程序大佬怎么实现了
比如他们可以直接快速选择是哪一家的标识符，并且能把存量的转化出来

**其他内容**

* CNGAL上
现在每次添加标识符都得手工打一个完整的链接，并且需要保证大小写完全不会出错
![图片](https://user-images.githubusercontent.com/42690037/167373289-e84e292c-cc0a-40e6-8058-128917dc747c.png)
并且标识符应该一般是不需要手动再输入一串描述文本的吧？
![图片](https://user-images.githubusercontent.com/42690037/167373517-1af451d3-a659-472d-bd97-5f2da848cb25.png)
然后才能看到效果，审核会不会也很费力？
![图片](https://user-images.githubusercontent.com/42690037/167373941-ccb15f94-4a5e-4bc9-9cce-34204df1eaed.png)

* VNDB上
而VNDB的编辑界面虽然不智能，但是它也只需要我把核心内容填进去就好
![图片](https://user-images.githubusercontent.com/42690037/167373727-161d2809-aa7d-462a-83a9-0da54729f713.png)

* Wikidata上
而Wikidata的编辑器是具有联想功能的，它显然是针对标识符做过针对性的优化，常见的各大索引都有对应的Property
![图片](https://user-images.githubusercontent.com/42690037/167373418-02b96e2e-a61e-4ff9-b3e3-1d8389657732.png)

**Comment by LittleFish-233** [comment]
我的想法是按VNDB的来，把常见的索引列出，直接填Id
（可能会写个脚本自动检索并添加

**Comment by LaoshuBaby** [comment]
> 常见的索引列出，直接填Id

挺好的，然后可以认为Bangumi/VNDB/Wikidata三种是常备id，然后其他的照常走传统方法，直到它变为频繁以后再说喵

**Comment by LaoshuBaby** [comment]
提出一个问题

![图片](https://user-images.githubusercontent.com/42690037/170057886-29d8984c-c5e5-48e9-8e3a-dfc2fd006325.png)

1. 似乎标识符目前没有引入正则匹配，不管是什么都会显示对号（具体的正则表达式我可以提供，但是我不会C#，就只能搁这儿当个司马产品经理提需求，啊不过完不成就扔这儿open着也没问题）

比如这个地方，VNDB只会有开头一个字母跟数字

2. 有时候用户会直接复制一整个链接进来，能否提供断句功能直接将网址中关键的标识符部分提取出来？（当然这个恐怕也得依靠正则表达式支持？）

~~**Fuck regex**~~

**Comment by LittleFish-233** [comment]
这个 √ 是上个组件库(bootstrapblazor)遗留下来的,之后计划全部替换为新组件库(masablazor)
(目前是新旧混杂的混乱时期

两个功能近期抽空弄一下

**Comment by LaoshuBaby** [comment]
> 这个 √ 是上个组件库(bootstrapblazor)遗留下来的,之后计划全部替换为新组件库(masablazor)

啊我还以为是特意加的格式验证没起作用（逃

**Comment by LittleFish-233** [comment]
> 有时候用户会直接复制一整个链接进来，能否提供断句功能直接将网址中关键的标识符部分提取出来？（当然这个恐怕也得依靠正则表达式支持？）

输入完整连接后按下回车或点击其他区域即可

![image](https://user-images.githubusercontent.com/53342258/170645551-902f34ea-a87b-4254-bef9-23edcdbfe579.png)

> 似乎标识符目前没有引入正则匹配，不管是什么都会显示对号（具体的正则表达式我可以提供，但是我不会C#，就只能搁这儿当个司马产品经理提需求，啊不过完不成就扔这儿open着也没问题）

这个放到把全部输入框换成新组件库的时候来弄（咕

@LaoshuBaby

**Comment by LittleFish-233** [comment]
鉴于自身能力有限，无法实现剩余功能，先关闭
